name: "vulnvisor"
repository: github.com/LucianErick/VulnVisor
version: "0.0.10"
usage: scan targets into a html dashboard file
description: |-
  A Trivy plugin that scans and outputs the results to a html dashboard file
  trivy vulnvisor [-h,--help] command target filename.

platforms:
  - selector:
      os: linux
      arch: amd64
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_linux-amd64.tar.gz
    bin: ./vulnvisor
  - selector:
      os: linux
      arch: arm
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_linux-arm.tar.gz
    bin: ./vulnvisor
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_linux-arm64.tar.gz
    bin: ./vulnvisor
  - selector:
      os: linux
      arch: s390x
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_linux-s390x.tar.gz
    bin: ./vulnvisor
  - selector:
      os: linux
      arch: ppc64le
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_linux-ppc64le.tar.gz
    bin: ./vulnvisor
  - selector:
      os: linux
      arch: 386
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_linux-386.tar.gz
    bin: ./vulnvisor

  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_darwin-amd64.tar.gz
    bin: ./vulnvisor
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_darwin-arm64.tar.gz
    bin: ./vulnvisor

  - selector:
      os: freebsd
      arch: 386
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_freebsd-386.tar.gz
    bin: ./vulnvisor
  - selector:
      os: freebsd
      arch: amd64
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_freebsd-amd64.tar.gz
    bin: ./vulnvisor

  - selector:
      os: windows
      arch: amd64
    uri: https://github.com/LucianErick/VulnVisor/releases/download/v0.0.10/VulnVisor_0.0.10_windows-amd64.zip
    bin: ./vulnvisor